version: "3"

services:
  php_nginx:
    depends_on:
      - php_app
    image: nginx:mainline-alpine-slim
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php_app
    volumes:
      - ./src:/var/www/public-html/app
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_app_tpl_networks

  php_app:
    depends_on:
      - db_app
    build:
      context: ./docker/php_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/public-html/app
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - db_app:db_host
    networks:
      - php_app_tpl_networks

  db_app:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./config/mysql.env
    volumes:
      - ./data/db_app:/var/lib/mysql
    networks:
      - php_app_tpl_networks

networks:
  php_app_tpl_networks:
    driver: bridge

volumes:
  db_app:
    driver: local

