version: "3"

services:
  php_nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php_app
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_app_tpl_networks

  php_app:
    depends_on:
      - db_app
    build:
      context: ./docker/php
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/public-html/app
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php/access.log:/usr/local/log/www.access.log
    links:
      - db_app:db_host
    networks:
      - php_app_tpl_networks

  db_app:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./config/mysql/mysql.env
    volumes:
      - ./data/db_app:/var/lib/mysql
    networks:
      - php_app_tpl_networks

networks:
  php_app_tpl_networks:
    driver: bridge

